# Cloudflare Tunnel Configuration for MailQueryWithMCP
# This configuration will proxy requests to your unified HTTP server

tunnel: mailquery-mcp
credentials-file: /home/kimghw/.cloudflared/mailquery-mcp.json

# Ingress rules
ingress:
  # Main application
  - hostname: mailquery-mcp.example.com
    service: http://localhost:8000
    originRequest:
      # Allow all headers
      noTLSVerify: true
      # Keep alive connections
      keepAliveConnections: 100
      keepAliveTimeout: 90s
      # HTTP/2 support
      http2Origin: true
      # Disable chunked encoding (for SSE/streaming)
      disableChunkedEncoding: false
      # Request timeout
      connectTimeout: 30s

  # Health check endpoint
  - hostname: health.mailquery-mcp.example.com
    service: http://localhost:8000
    path: /health

  # Catch-all rule (required)
  - service: http_status:404